title: Rodrigo Vicente
author:
  name: Rodrigo Vicente
  email: rvicente@ifae.es
description: > # this means to ignore newlines until "show_excerpts:"
  Juan de la Cierva Postdoctoral Fellow at Institut de Física d'Altes Energies (IFAE) in 
  Barcelona, working on the intersection of strong gravity and BSM physics.
show_excerpts: false # set to true to show excerpts on the homepage

# Minima date format
# refer to https://shopify.github.io/liquid/filters/date/ if you want to customize this
minima:
  date_format: "%b %-d, %Y"

  # generate social links in footer
  social_links:
    - { platform: google_scholar, user_url: "https://scholar.google.com/citations?user=sEEKTLcAAAAJ&hl=en" }
    - { platform: twitter,        user_url: "https://twitter.com/rodrigovice93" }

# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
#header_pages:
# - about.md

# Build settings
markdown: kramdown
remote_theme: jekyll/minima

plugins:
 - jekyll-feed
 - jekyll-seo-tag
